# T1 Agent Benchmark Test Suite

sai_tx_slow_path_rate-sai_impl
sai_rx_slow_path_rate-sai_impl
sai_ecmp_shrink_speed-sai_impl
sai_rib_resolution_speed-sai_impl
sai_ecmp_shrink_with_competing_route_updates_speed-sai_impl
sai_fsw_scale_route_add_speed-sai_impl
sai_stats_collection_speed-sai_impl
sai_init_and_exit_100Gx100G-sai_impl
sai_switch_reachability_change_speed-sai_impl
