genrule(
    name = "fboss_builder_docker",
    visibility = ["//visibility:public"],
    srcs = [
        "fboss/oss/scripts/build_docker.sh",
        "fboss/oss/docker/Dockerfile.builder",
        "fboss/oss/docker/Dockerfile.builder.dockerignore",
    ] + glob(["build/**"]),
    outs = ["fboss_builder.tar"],
    cmd = """
        $(SRCS)/fboss/oss/scripts/build_docker.sh
        docker save -o fboss_builder.tar fboss_builder
        mv fboss_builder.tar $(RULEDIR)
    """,
    local=True,
)

sh_library(
    name = "run_in_builder",
    visibility = ["//visibility:public"],
    srcs = ["fboss/oss/scripts/run_in_builder.sh"],
)
