load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")

oncall("fboss_optics_phy")

cpp_library(
    name = "nova4000_bsp",
    srcs = [
        "Nova4000BspPlatformMapping.cpp",
    ],
    headers = [
        "Nova4000BspPlatformMapping.h",
    ],
    exported_deps = [
        "//fboss/lib/bsp:bsp_platform_mapping_lib",
        "//thrift/lib/cpp2/protocol:protocol",
    ],
)
