name: Nexthop Manual Build

# Manually trigger build
on:
  workflow_dispatch:
    inputs:
      organization:
        description: 'Organization'
        required: true
        default: 'nexthop-ai'
      branch:
        description: 'Branch Name'
        required: true
        default: 'main'
      platform:
        description: 'Platform'
        required: true
        type: choice
        options:
          - broadcom
          - mellanox
          - vs
        default: broadcom
      target:
        description: 'Target'
        required: false
        default: default
        type: choice
        options:
          - aboot
          - default
      build-type:
        description: "Build type"
        required: false
        type: choice
        options:
          - nightly
          - release
          - sync
          - user
        default: user
      keep_vm:
        description: 'Keep VM after build'
        required: false
        type: boolean
        default: false
      nh_options:
        description: 'Additional build options'
        required: false
        type: string
        default: ''
      build_debug:
        # We have to have this option because nexis passes it in, and if the
        # option isn't here then triggering the workflow will silently fail.
        description: "Not used in FBOSS"
        required: false
        type: boolean
        default: false


jobs:
  build-image:
    permissions:
      id-token: write
      contents: read
    uses: nexthop-ai/nh/.github/workflows/build.reusable.yml@main
    with:
      # For PR events: use PR branch name
      # For workflow_dispatch: use the input branch name
      organization: ${{ github.event.inputs.organization || 'nexthop-ai' }}
      repo: nh/private-fboss
      branch: ${{ github.event.inputs.branch || github.head_ref || github.ref_name }}
      platform: ${{ github.event.inputs.platform || 'broadcom' }}
      target: ${{ github.event.inputs.target || 'default' }}
      user: ${{ github.event.inputs.build-type == 'nightly' && 'taskrabbit' || github.actor }}
      keep_vm: ${{ github.event.inputs.keep_vm != null && fromJson(github.event.inputs.keep_vm) || false }}
      nh_options: ${{ github.event.inputs.nh_options || '' }}
      build_debug: false
      build-type: ${{ github.event.inputs.build-type }}
      jobs: 32
      vm_size: 32-256
    name: Build Image

  build-summary:
    needs: build-image
    uses: nexthop-ai/nh/.github/workflows/build-summary.reusable.yml@main
    if: ${{ always() }}
    name: Build Summary
