name: Distro Image Build
run-name: Distro Image Build

on:
  pull_request:
  # Allow manually triggering the workflow
  workflow_dispatch:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
  Distro-Image-Build:
    runs-on: cloudstack-ubuntu24-large
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6

      - name: Setup NHTools
        run: |
          set -e
          echo "${{ secrets.RABBIT_NEXTHOP_PAT }}" | gh auth login --with-token
          docker pull container-registry.sw.internal.nexthop.ai:443/nhtools:latest > /dev/null 2>&1
          INSTALLER=/usr/local/bin/nhtools-install
          docker run --rm --entrypoint=/bin/cat container-registry.sw.internal.nexthop.ai:443/nhtools:latest /nhtools/nhtools-install | sudo install -m 755 -o root -g root /dev/stdin /usr/local/bin/nhtools-install
          sudo /usr/local/bin/nhtools-install /usr/local/bin
          sudo sed -i -e 's/^search.*//' /etc/resolv.conf
          echo "search internal.nexthop.ai" | sudo tee -a /etc/resolv.conf > /dev/null

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::867344435357:role/GitHubActions-EC2-Role
          aws-region: us-east-2
          role-duration-seconds: 14400 # 4 hours timeout
          output-env-credentials: true

      - name: Run fboss-image build
        run: |
          ./fboss-image/distro_cli/fboss-image build fboss-image/from_source.json
          BRANCH="${{ github.head_ref || github.ref_name }}"
          build_id=$(nexis-buildrunner init --repo private-fboss --branch "$BRANCH" --platform xgs)
          nexis-buildrunner upload --build-id $build_id --image fboss-distro-image_usb.iso
          nexis-buildrunner upload --build-id $build_id --image fboss-distro-image_pxe.tar
          nexis-buildrunner upload --build-id $build_id --image fboss-distro-image_onie.bin
          nexis-buildrunner commit --build-id $build_id
