name: Distro Image Build
run-name: Distro Image Build

on:
  pull_request:
  # Allow manually triggering the workflow
  workflow_dispatch:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
  Distro-Image-Build:
    runs-on: cloudstack-ubuntu24-large
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6

      - name: Setup NHTools
        uses: nexthop-ai/nh/.github/actions/install-nhtools@main
        with:
          token: ${{ secrets.RABBIT_NEXTHOP_PAT }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::867344435357:role/GitHubActions-EC2-Role
          aws-region: us-east-2
          role-duration-seconds: 14400 # 4 hours timeout
          output-env-credentials: true

      - name: Run fboss-image build
        run: |
          ./fboss-image/distro_cli/fboss-image build fboss-image/from_source.json
