name: Monobuild

on:
  workflow_dispatch:
  pull_request:
  merge_group:
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  monobuild:
    permissions:
      id-token: write
      contents: read
    uses: nexthop-ai/nh/.github/workflows/monobuild.reusable.yml@main
    with:
      submodule: fboss
      nh_branch: main
    secrets:
      GH_TOKEN: ${{ secrets.RABBIT_NEXTHOP_PAT }}
    name: Monobuild
