name: PR Title Check

on:
  merge_group:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  pr-title-check:
    uses: nexthop-ai/nh/.github/workflows/pr-title-check.reusable.yml@main
    with:
      require_iss: false
