name: PR Workflow

# Trigger the workflow on pull requests
on:
  pull_request:
  workflow_dispatch: # Allow manual triggering.

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  # TODO: Some day build and run a smoke test, like we do for in the
  # sonic-buildimage pr.yml
  build-image:
    name: Build FBOSS Image
    permissions:
      id-token: write
      contents: read
    uses: nexthop-ai/nh/.github/workflows/build.reusable.yml@main
    with:
      # For PR events: use PR branch name
      # For workflow_dispatch: use the input branch name
      organization: nexthop-ai
      repo: private-fboss
      branch: ${{ github.head_ref }}
      platform: broadcom
      target: default
      user: ${{ github.event_name == 'pull_request' && github.event.pull_request.user.login || github.event_name == 'workflow_dispatch' && github.actor }}
      keep_vm: false
      nh_options: ''
      build-type: user
      build_debug: false
      jobs: 16
      vm_size: 16-128
